dev_editor_homepage:
    path:     /editor
    defaults: { _controller: DEVEditorBundle:Editor:index }

dev_editor_add_news:
    path:     /editor/add/actu/{id}
    defaults: { _controller: DEVEditorBundle:Editor:addActu, id:0 }

dev_editor_add_article:
    path:     /editor/add/article/{id}
    defaults: { _controller: DEVEditorBundle:Editor:addArticle, id:0 }
    
dev_editor_add_doc:
    path:     /editor/add/doc
    defaults: { _controller: DEVEditorBundle:Editor:uploadDoc }

dev_editor_list_news:
    path:     /editor/list/actu
    defaults: { _controller: DEVEditorBundle:Editor:listActu }
    
dev_editor_list_articles:
    path:     /editor/list/articles
    defaults: { _controller: DEVEditorBundle:Editor:listArticle }
    
dev_editor_list_doc:
    path:     /editor/list/document
    defaults: { _controller: DEVEditorBundle:Editor:listDoc }
    
dev_editor_suppr_news:
    path:     /editor/suppr/actu/{id}
    defaults: { _controller: DEVEditorBundle:Editor:delActu }
    
dev_editor_suppr_article:
    path:     /editor/suppr/article/{id}
    defaults: { _controller: DEVEditorBundle:Editor:delArticle }
    
dev_editor_suppr_doc:
    path:     /editor/suppr/doc/{id}
    defaults: { _controller: DEVEditorBundle:Editor:delDoc }