parameters:
#    dev_editor.example.class: DEV\EditorBundle\Example

services:
#    dev_editor.example:
#        class: %dev_editor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
