dev_main_homepage:
    pattern:  /
    defaults: { _controller: DEVMainBundle:Main:index }
    options:
        expose:   true

dev_main_scoutismepage:
    pattern:  /scoutisme
    defaults: { _controller: DEVMainBundle:Main:scoutisme }
    
dev_main_view_actu:
    pattern:  /view/actu/{id}
    defaults: { _controller: DEVMainBundle:Main:displayActu }
    options:
        expose:   true