<?php

namespace DEV\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActuRepository extends EntityRepository
{
}
